name: Update Filtered EPG

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gzip python3

      - name: Download EPG from epg.one
        run: |
          curl -L "http://epg.one/epg2.xml.gz" -o epg2.xml.gz

      - name: Run EPG filter
        run: |
          python3 filter_epg.py

      - name: Commit filtered EPG
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add epg_su_filtru.xml.gz || true
          git commit -m "Auto-update filtered EPG" || true
          git push